# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='updated',
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.CharField(default=None, max_length=254, null=True),
        ),
    ]
